# Generated by Django 4.2.17 on 2024-12-12 08:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
